version: "3.8"

services:
  web:
    build: .
    container_name: chatbot_web
    restart: always
    environment:
      DEBUG: "False"
      ALLOWED_HOSTS: "*"
      GOOGLE_OAUTH2_CLIENT_ID: "SEU_CLIENT_ID"
      GOOGLE_OAUTH2_CLIENT_SECRET: "SEU_CLIENT_SECRET"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "chatgpt_project.wsgi:application"]
